name: "SimpleBroadcast"
version: 1.1
main: me.crackleharvest36.pmplus.Main

commands:
  msg:
    usage: /msg [<player>] [<message>]
    description: "Message a player on the server."
    aliases: [tell, w]
  reply:
    usage: /reply [<message>]
    description: "Respond faster to a player you messaged"
    aliases: [r]
